ECOS-10868 (JSON beolvasás)
GRAPHISOFT/favorite-converter pull request #7
Opened 2024-09-05 14:15 UTC by ak-nagy

2024-09-05 18:29 UTC, palenikm requested changes

2024-09-05 18:29 UTC, palenikm commented on Src/RenamedParametersInfo.hpp
> +    std::vector<RenamedParameter> renamedParameters;
As I examined the original script I think this should be std::map (or unordered map) because of the easier use. (Same will be applied to the csv import)

2024-09-05 19:11 UTC, palenikm commented on include/rapidjson/allocators.h
> +#include "rapidjson.h"
API DevKit 28 has contained rapidJSON already.

2024-09-06 08:20 UTC, ak-nagy commented on Src/RenamedParametersInfo.hpp
> +    std::vector<RenamedParameter> renamedParameters;
Yes, we can handle it like that. I've changed it to std::unordered_map<std::string, std::string> with two new using for std::string (OldName, NewName).

2024-09-06 08:21 UTC, ak-nagy commented on include/rapidjson/allocators.h
> +#include "rapidjson.h"
You are absolutely right. I've removed the newly added include folder and the related cmake changes. Now, we are using the RapidJSON from the APIDevKit. Thanks!

2024-09-10 05:25 UTC, palenikm approved these changes
Thanks for the changes!

2024-09-10 05:26 UTC, merged